# -*- coding: utf-8 -*-
"""shap_class_rf.ipynb_work

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlusmZvXwVHHip76XEBOqixpc7SYcvzF
"""

# Commented out IPython magic to ensure Python compatibility.
#gitからダウンロード
# %env TOKEN=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
!git clone https://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@github.com/fukazawa-lab/shap-class.git

!pip install japanize_matplotlib datasets fsspec==2024.6.1 shap

import os

# ディレクトリを 'shap-class' に変更
os.chdir('/content/shap-class')

# 現在の作業ディレクトリを確認
print("Current working directory:", os.getcwd())

from importlib import reload
from file_check import check_files
from classification import ml_numerical_classification_rf
from classification import cm
from regression import ml_numerical_regression_rf


from classification import ml_numerical_classification_rf
from classification import ml_numerical_classification_xgb
from classification import ml_numerical_classification_lgb

"""# ファイル格納
* shap-class/dataset配下にtrain_num.csvとvalidation_num.csvファイルをおいてください。 特徴量のカラム名、数は任意です。ただし、目的変数のカラム名はlabelにしてください。
"""

reload(check_files)

check_files.validate_target_column("dataset/train_num.csv")
check_files.validate_target_column("dataset/validation_num.csv")
check_files.check_class_difference("dataset/train_num.csv", "dataset/validation_num.csv","label")

reload(check_files)
check_files.visualize_labels("dataset/train_num.csv", "label")
check_files.visualize_labels( "dataset/validation_num.csv", "label")

"""ラベルの数が同数くらいを目指してほしい

# モデル構築＆解釈

以下、これを使う
"""

reload(ml_numerical_classification_rf)
ml_numerical_classification_rf.train_and_evaluate_model('dataset', 'train_num.csv', 'validation_num.csv')

cm.vis('results/classification/confusion_matrix_num_rf.csv','results/classification/result_num_rf.csv')

"""以下はやる必要がない"""

reload(ml_numerical_classification_xgb)
ml_numerical_classification_xgb.train_and_evaluate_model('dataset', 'train_num.csv', 'validation_num.csv')

cm.vis('results/classification/confusion_matrix_num_xgb.csv','results/classification/result_num_xgb.csv')

reload(ml_numerical_classification_lgb)
ml_numerical_classification_lgb.train_and_evaluate_model('dataset', 'train_num.csv', 'validation_num.csv')

cm.vis('results/classification/confusion_matrix_num_lgb.csv','results/classification/result_num_lgb.csv')